#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
# Source0 file verified with key 0x3353C9CEF108B584 (mdroth@utexas.edu)
#
Name     : qemu
Version  : 7.2.1
Release  : 160
URL      : https://download.qemu.org/qemu-7.2.1.tar.xz
Source0  : https://download.qemu.org/qemu-7.2.1.tar.xz
Source1  : https://download.qemu.org/qemu-7.2.1.tar.xz.sig
Summary  : OpenBIOS development utilities
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-2-Clause-Patent BSD-3-Clause BSD-4-Clause CC0-1.0 GPL-2.0 GPL-2.0+ GPL-3.0 LGPL-2.1 LGPL-2.1+ LGPL-3.0 MIT OpenSSL
BuildRequires : SDL2_image-dev
BuildRequires : attr-dev
BuildRequires : automake-dev
BuildRequires : bison
BuildRequires : buildreq-configure
BuildRequires : ceph-dev
BuildRequires : flex
BuildRequires : glib-dev
BuildRequires : gtk3-dev
BuildRequires : libaio-dev
BuildRequires : libcap-dev
BuildRequires : libcap-ng-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libseccomp-dev
BuildRequires : libslirp-dev
BuildRequires : libssh-dev
BuildRequires : libssh2-dev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : liburing-dev
BuildRequires : m4
BuildRequires : nfs-utils-dev
BuildRequires : numactl-dev
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(libcacard)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pypi(sphinx_rtd_theme)
BuildRequires : pypi-sphinx
BuildRequires : snappy-dev
BuildRequires : spice
BuildRequires : spice-dev
BuildRequires : spice-protocol
BuildRequires : usbredir-dev
BuildRequires : util-linux-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Allow-unknown-options-in-configure-script.patch
Patch2: 0002-Set-default-number-of-sockets-to-1.patch
Patch3: 0003-Use-run-lock.patch

%description
This package contains the OpenBIOS development utilities.

There are
* toke - an IEEE 1275-1994 compliant FCode tokenizer
* detok - an IEEE 1275-1994 compliant FCode detokenizer
* paflof - a forth kernel running in user space
* an fcode bytecode evaluator running in paflof

See /usr/share/doc/packages/openbios for details and examples.

Authors:
--------
    Stefan Reinauer <stepan@openbios.net>
    Segher Boessenkool <segher@openbios.net>

%prep
%setup -q -n qemu-7.2.1
cd %{_builddir}/qemu-7.2.1
%patch1 -p1
%patch2 -p1
%patch3 -p1
pushd ..
cp -a qemu-7.2.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1680798256
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
%configure --disable-static --enable-sdl \
--enable-vnc \
--enable-gtk \
--enable-kvm \
--disable-strip \
--target-list='i386-softmmu x86_64-softmmu i386-linux-user x86_64-linux-user' \
--enable-spice \
--enable-rbd \
--extra-cflags="-O3" \
--enable-attr \
--enable-cap-ng \
--enable-virtfs \
--enable-vhost-net \
--enable-usb-redir \
--python=/usr/bin/python \
--enable-seccomp \
--enable-linux-aio \
--audio-drv-list='pa,alsa,oss,sdl' \
--disable-curses \
--enable-lto \
--enable-linux-io-uring
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static --enable-sdl \
--enable-vnc \
--enable-gtk \
--enable-kvm \
--disable-strip \
--target-list='i386-softmmu x86_64-softmmu i386-linux-user x86_64-linux-user' \
--enable-spice \
--enable-rbd \
--extra-cflags="-O3" \
--enable-attr \
--enable-cap-ng \
--enable-virtfs \
--enable-vhost-net \
--enable-usb-redir \
--python=/usr/bin/python \
--enable-seccomp \
--enable-linux-aio \
--audio-drv-list='pa,alsa,oss,sdl' \
--disable-curses \
--enable-lto \
--enable-linux-io-uring
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1680798256
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qemu
cp %{_builddir}/qemu-%{version}/COPYING %{buildroot}/usr/share/package-licenses/qemu/2b9d60c2972b476384af9900276837ac81954e80 || :
cp %{_builddir}/qemu-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/qemu/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/qemu-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/qemu/c690b05ff6431c277b59784e95169e0e0528a983 || :
cp %{_builddir}/qemu-%{version}/dtc/README.license %{buildroot}/usr/share/package-licenses/qemu/a6759c569917866b44961c88629ae4f3f07ea686 || :
cp %{_builddir}/qemu-%{version}/meson/COPYING %{buildroot}/usr/share/package-licenses/qemu/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/qemu-%{version}/meson/packaging/License.rtf %{buildroot}/usr/share/package-licenses/qemu/00dcd169768382e0b6a13d0d110266754fedb62b || :
cp %{_builddir}/qemu-%{version}/meson/packaging/macpages/English.lproj/license.html %{buildroot}/usr/share/package-licenses/qemu/ed59b8ab4e260b632c935598bf0d1472e4e2dbdf || :
cp %{_builddir}/qemu-%{version}/roms/QemuMacDrivers/COPYING %{buildroot}/usr/share/package-licenses/qemu/2b9d60c2972b476384af9900276837ac81954e80 || :
cp %{_builddir}/qemu-%{version}/roms/SLOF/LICENSE %{buildroot}/usr/share/package-licenses/qemu/e1f0ad62e4850a19b1f56b821f37fccbf84ec191 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/.pytool/Plugin/LicenseCheck/LicenseCheck_plug_in.yaml %{buildroot}/usr/share/package-licenses/qemu/f1a6a8f321d20cb5fbec859a848bff49ad31de69 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/ArmPkg/Library/ArmSoftFloatLib/berkeley-softfloat-3/COPYING.txt %{buildroot}/usr/share/package-licenses/qemu/c4cd5ba6f665cf9ecb44e0620c2c76140566cfc6 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/BaseTools/Source/C/BrotliCompress/brotli/LICENSE %{buildroot}/usr/share/package-licenses/qemu/c045813a6c514f2d30d60a07c6aaf3603850e608 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/CryptoPkg/Library/OpensslLib/openssl/LICENSE %{buildroot}/usr/share/package-licenses/qemu/607e96d7bc75d9f884a8e210d276cca4006e0753 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/CryptoPkg/Library/OpensslLib/openssl/external/perl/Text-Template-1.46/COPYING %{buildroot}/usr/share/package-licenses/qemu/ab8577d3eb0eedf3f98004e381a9cee30e7224e1 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/License-History.txt %{buildroot}/usr/share/package-licenses/qemu/1b5c06f43bf6e2039065b681398f6b99a4d552f8 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/License.txt %{buildroot}/usr/share/package-licenses/qemu/7fc5c71d1c403b07043376504d62f2ac73a75313 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/MdeModulePkg/Library/BrotliCustomDecompressLib/brotli/LICENSE %{buildroot}/usr/share/package-licenses/qemu/c045813a6c514f2d30d60a07c6aaf3603850e608 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/MdeModulePkg/Universal/RegularExpressionDxe/oniguruma/COPYING %{buildroot}/usr/share/package-licenses/qemu/fa8fca82526cc5174bb568accab23c3eb9c049ea || :
cp %{_builddir}/qemu-%{version}/roms/edk2/OvmfPkg/Bhyve/License.txt %{buildroot}/usr/share/package-licenses/qemu/6b5c7cbcd561ea8f6bba9dd24393f995c1a006e9 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/OvmfPkg/License.txt %{buildroot}/usr/share/package-licenses/qemu/c9c057d4dc70e7a834d80b762663ca01a852ed13 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/RedfishPkg/Library/JsonLib/jansson/LICENSE %{buildroot}/usr/share/package-licenses/qemu/fa82ae23fff791a399cb3c72b59fe7199e989652 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/UnitTestFrameworkPkg/Library/CmockaLib/cmocka/COPYING %{buildroot}/usr/share/package-licenses/qemu/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/UnitTestFrameworkPkg/Library/CmockaLib/cmocka/cmake/Modules/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/qemu/ff3ed70db4739b3c6747c7f624fe2bad70802987 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/UnitTestFrameworkPkg/Library/CmockaLib/cmocka/doc/that_style/LICENSE %{buildroot}/usr/share/package-licenses/qemu/86b52f0f7e15225010495c0b221b79ef0dc1a90d || :
cp %{_builddir}/qemu-%{version}/roms/ipxe/COPYING %{buildroot}/usr/share/package-licenses/qemu/cedc99c80ddc135681756e652d55c72d89ebdfe7 || :
cp %{_builddir}/qemu-%{version}/roms/ipxe/COPYING.GPLv2 %{buildroot}/usr/share/package-licenses/qemu/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/qemu-%{version}/roms/ipxe/src/include/ipxe/efi/LICENCE %{buildroot}/usr/share/package-licenses/qemu/ca46b2cea92edc93654b11c06c0073ec1a2e50e8 || :
cp %{_builddir}/qemu-%{version}/roms/openbios/COPYING %{buildroot}/usr/share/package-licenses/qemu/8b35225cbdbd6858fb081817cc9dbfe4bef26f5b || :
cp %{_builddir}/qemu-%{version}/roms/openbios/Documentation/kernel/COPYING %{buildroot}/usr/share/package-licenses/qemu/e9b568889ca9075b505c509f7a877a723cc9a4b0 || :
cp %{_builddir}/qemu-%{version}/roms/openbios/utils/devbios/COPYING %{buildroot}/usr/share/package-licenses/qemu/7475b0da13789cd598fe0703f5337d37dd8b0b95 || :
cp %{_builddir}/qemu-%{version}/roms/opensbi/COPYING.BSD %{buildroot}/usr/share/package-licenses/qemu/0a0d7ae8e993794ae9c9ac5219c3d2bbf289471f || :
cp %{_builddir}/qemu-%{version}/roms/qboot/LICENSE %{buildroot}/usr/share/package-licenses/qemu/30a6e0a424471d8ac874b5616dd5a18c45fd6046 || :
cp %{_builddir}/qemu-%{version}/roms/qemu-palcode/COPYING %{buildroot}/usr/share/package-licenses/qemu/2b9d60c2972b476384af9900276837ac81954e80 || :
cp %{_builddir}/qemu-%{version}/roms/seabios-hppa/COPYING %{buildroot}/usr/share/package-licenses/qemu/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/qemu-%{version}/roms/seabios-hppa/COPYING.LESSER %{buildroot}/usr/share/package-licenses/qemu/e7d563f52bf5295e6dba1d67ac23e9f6a160fab9 || :
cp %{_builddir}/qemu-%{version}/roms/seabios/COPYING %{buildroot}/usr/share/package-licenses/qemu/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/qemu-%{version}/roms/seabios/COPYING.LESSER %{buildroot}/usr/share/package-licenses/qemu/e7d563f52bf5295e6dba1d67ac23e9f6a160fab9 || :
cp %{_builddir}/qemu-%{version}/roms/sgabios/COPYING %{buildroot}/usr/share/package-licenses/qemu/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/LICENCE %{buildroot}/usr/share/package-licenses/qemu/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/ccan/array_size/LICENSE %{buildroot}/usr/share/package-licenses/qemu/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/ccan/build_assert/LICENSE %{buildroot}/usr/share/package-licenses/qemu/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/ccan/check_type/LICENSE %{buildroot}/usr/share/package-licenses/qemu/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/ccan/container_of/LICENSE %{buildroot}/usr/share/package-licenses/qemu/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/ccan/endian/LICENSE %{buildroot}/usr/share/package-licenses/qemu/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/ccan/heap/LICENSE %{buildroot}/usr/share/package-licenses/qemu/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/ccan/list/LICENSE %{buildroot}/usr/share/package-licenses/qemu/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/ccan/short_types/LICENSE %{buildroot}/usr/share/package-licenses/qemu/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/ccan/str/LICENSE %{buildroot}/usr/share/package-licenses/qemu/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/libstb/crypto/mbedtls/LICENSE %{buildroot}/usr/share/package-licenses/qemu/4d6c5af1a9cc4eaab3b93353fc166d8e29c150c6 || :
cp %{_builddir}/qemu-%{version}/roms/u-boot-sam460ex/COPYING %{buildroot}/usr/share/package-licenses/qemu/11bb99995c221415712bb5a6d6c0898f02936feb || :
cp %{_builddir}/qemu-%{version}/roms/u-boot-sam460ex/board/ACube/bios_emulator/scitech/src/x86emu/LICENSE %{buildroot}/usr/share/package-licenses/qemu/3f226d574cd9547c3e4d934bb1ac4be3601a9782 || :
cp %{_builddir}/qemu-%{version}/roms/u-boot-sam460ex/fs/jffs2/LICENCE %{buildroot}/usr/share/package-licenses/qemu/2f02ed32418afe8cc25f30f269c63085bafe44f7 || :
cp %{_builddir}/qemu-%{version}/roms/u-boot/fs/jffs2/LICENCE %{buildroot}/usr/share/package-licenses/qemu/2f02ed32418afe8cc25f30f269c63085bafe44f7 || :
cp %{_builddir}/qemu-%{version}/roms/vbootrom/LICENSE %{buildroot}/usr/share/package-licenses/qemu/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/qemu-%{version}/subprojects/libvfio-user/LICENSE %{buildroot}/usr/share/package-licenses/qemu/36fb901125ffda91bbec1cab3efc5c9f8f2d15a7 || :
cp %{_builddir}/qemu-%{version}/tests/fp/berkeley-softfloat-3/COPYING.txt %{buildroot}/usr/share/package-licenses/qemu/c4cd5ba6f665cf9ecb44e0620c2c76140566cfc6 || :
cp %{_builddir}/qemu-%{version}/tests/fp/berkeley-testfloat-3/COPYING.txt %{buildroot}/usr/share/package-licenses/qemu/b91b6ebd4f4725457f64e1d35e5a94c2bd35bcec || :
cp %{_builddir}/qemu-%{version}/tests/lcitool/libvirt-ci/COPYING %{buildroot}/usr/share/package-licenses/qemu/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/qemu-%{version}/tests/uefi-test-tools/LICENSE %{buildroot}/usr/share/package-licenses/qemu/234e74aeab28f7faad2baccf1a3f943b36ab895e || :
cp %{_builddir}/qemu-%{version}/ui/keycodemapdb/LICENSE.BSD %{buildroot}/usr/share/package-licenses/qemu/ea5b412c09f3b29ba1d81a61b878c5c16ffe69d8 || :
cp %{_builddir}/qemu-%{version}/ui/keycodemapdb/LICENSE.GPL2 %{buildroot}/usr/share/package-licenses/qemu/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/bin/qemu-ga
rm -f %{buildroot}*/usr/share/qemu/u-boot.e500
rm -f %{buildroot}*/usr/share/man/man7/qemu-ga-ref.7
rm -f %{buildroot}*/usr/share/man/man8/qemu-ga.8
rm -f %{buildroot}*/usr/share/doc/qemu/.buildinfo
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name} --skip-path /usr/libexec/qemu-bridge-helper

%files
%defattr(-,root,root,-)
